### ISSUE TITLE
Rowspan for Subgroup

### ISSUE THREAD

**Issue by clavinovahan** [DataTables/RowGroup#21]
For subgroup, is it possible to show as td with rowspan, something like columns "customerName" and "productLine" in the example below,

https://www.koolreport.com/examples/reports/datagrid/rowgroup_rowspan/

Thanks.

**Comment by AllanJard** [comment]
Hi - sorry for the delayed reply. Support questions are [generally better in the forums](//datatables.net/forums).

The answer is no I'm sorry to say at the moment. It is possible to do if using server-side processing (since the cells get thrown away on each draw), but not with client-side processing I'm afraid.
