### ISSUE TITLE
RowGroup in combination with ColReorder problem

### ISSUE THREAD

**Issue by alexookah** [DataTables/RowGroup#3]
Hello,
i tried to use rowGroup with ColReorder and when i move the grouped column and refresh the page the groupping changes because the column index has changed.
the only way i have found is only to use fixedColumnsLeft/fixedColumnsRight to disable column reordering.

Is there a way to keep in sync the groupping Column when moving the column around?

i tried to handle this issue like this:

mark the column that i want to have groupping from html 

`<th group="yes">Groupping Column</th>`

and when initializing datatable:

```
var table = $('#datatable-responsive').DataTable({
    //Cell Reorder and save
    colReorder: true
    stateSave:  true,
    //RowGroup
    rowGroup: {
        dataSrc: 4,
    },
    initComplete: function(settings, json) {
        loadCorrectGroupingColumn() 
    }
});

function loadCorrectGroupingColumn() {
    table.rowGroup().dataSrc( $("[group='yes']").attr("data-column-index") );
}
```

but i cant run the table due to scope issues i think.

**Comment by DataTables** [comment]
Could you post support requests in the [DataTables forums](//datatables.net/forums) as the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md) that GitHub links to on opening a new request mentions please. I'm sorry if that document wasn't clear enough on that topic.

Regarding this question, I would suggest that you use [objects for your data source](https://datatables.net/manual/data/#Objects) rather than arrays. If you do that, I believe this issue will simply "go away"! The problem is that ColReorder really does change the order of the columns, so `rowGroup.dataSrc` would also have to be changed. That can be done with the events, but using objects is the easiest option.
